package vacademy.io.assessment_service.features.assessment.enums;

public enum ParticipantsCreationEnum {

    PUBLIC_REGISTRATIONS,
    PRIVATE_REGISTRATIONS,
    CLOSED_SELECT_BATCH,
    CLOSED_SELECT_STUDENT,
    CLOSED_LINK,
    NOTIFY_PARTICIPANTS,
    NOTIFY_PARENTS,
    REGISTRATION_CLOSE_DATE,
    REGISTRATION_OPEN_DATE,
    REGISTRATION_FORM_FIELDS,
    OPEN_SELECT_BATCH,
    OPEN_SELECT_STUDENT,
    OPEN_LINK
}
