apiVersion: v1
kind: Service
metadata:
  name: admin-core-service
  namespace: vacademy
  labels:
    app: admin-core-service
spec:
  selector:
    app: admin-core-service
  ports:
  - port: {{ .Values.services.admin_core_service.port }}
    targetPort: {{ .Values.services.admin_core_service.port }}
    protocol: TCP
  type: ClusterIP
