apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: vacademy
  labels:
    app: assessment-service
spec:
  selector:
    app: assessment-service
  ports:
  - port: {{ .Values.services.assessment_service.port }}
    targetPort: {{ .Values.services.assessment_service.port }}
    protocol: TCP
  type: ClusterIP
