apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: vacademy
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.services.auth_service.image.repository }}:{{ .Values.services.auth_service.image.tag }}"
          imagePullPolicy: {{ .Values.services.auth_service.image.pullPolicy | default "Always" }}
          env:
          {{- range $key, $value := .Values.globalEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
          livenessProbe:
            httpGet:
              path: /auth-service/actuator/health
              port: {{ .Values.services.auth_service.port }}
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /auth-service/actuator/health
              port: {{ .Values.services.auth_service.port }}
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /auth-service/actuator/health
              port: {{ .Values.services.auth_service.port }}
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: {{ .Values.services.auth_service.port }}
