apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: vacademy
  labels:
    app: community-service
spec:
  selector:
    app: community-service
  ports:
  - port: {{ .Values.services.community_service.port }}
    targetPort: {{ .Values.services.community_service.port }}
    protocol: TCP
  type: ClusterIP
