apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: vacademy
  labels:
    app: media-service
spec:
  selector:
    app: media-service
  ports:
  - port: {{ .Values.services.media_service.port }}
    targetPort: {{ .Values.services.media_service.port }}
    protocol: TCP
  type: ClusterIP
