"""GSAP animation scanner — extracts on-screen visual events from the
generated HTML/JS of each shot, so the sound planner can place SFX on
events a real-world version of the scene would actually be audible for.

Replaces the old "sound on every cut" / "sound per shot type" model with
a pure event-driven model. Outputs per-shot lists of:

    {t: <seconds-from-shot-start>, role: <sfx role>, label: <kind>,
     volume_mul: <float>, duration: <event duration s>}

Attached to each timeline entry as `entry["_sfx_events"]`. The sound
planner reads this list FIRST when emitting cues (see sound_planner.py
Rule A) and only falls back to Director sync_points for events the
scanner missed.

Design notes:
  - Regex-only parser. The HTML/JS is generated by the LLM in known
    patterns; an AST parser would be overkill and brittle against
    template variations.
  - Conservative: when we can't classify an animation confidently, emit
    nothing (silence is the correct default per the rewrite).
  - Stagger collapse: a per-character SplitText reveal could spawn 30
    events, which would flood the mix. We collapse staggered streams
    into ONE event at the start of the stream and let the SFX file
    cover the duration (e.g. a 1.5s typewriter clatter clip).
  - Skill events stay separate (sound_planner Rule C) — this scanner
    is purely about GSAP/CSS animation events.

Public API: `scan_events(html: str, shot_duration_s: float) -> List[Event]`
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

_log = logging.getLogger(__name__)


@dataclass
class GsapEvent:
    """One detected on-screen event ripe for SFX.

    `t` is RELATIVE to the shot's start. `role` is the sound_planner
    palette role to fire. `label` is descriptive ("typewriter",
    "bar_grow", "slide_in" etc.) — used in cue ids + prompt context.
    `volume_mul` defaults reflect "subtle/supportive" — these are
    sounds for visual confirmation, not stings."""
    t: float
    role: str
    label: str
    volume_mul: float = 0.7
    duration: float = 0.5  # how long the visual event lasts (informs SFX gen length)

    def as_dict(self) -> Dict[str, Any]:
        return {
            "t": round(self.t, 3),
            "role": self.role,
            "label": self.label,
            "volume_mul": round(self.volume_mul, 2),
            "duration": round(self.duration, 3),
        }


# ─────────────────────────────────────────────────────────────────────
# Animation classifier
# ─────────────────────────────────────────────────────────────────────
#
# Each rule inspects the `to` state (what the animation ends with) and
# `from` state (what it starts with) of a GSAP call. The classifier
# returns (role, label, volume_mul) or None when nothing matches —
# matching nothing means silence, which is the right default.

@dataclass
class _CallContext:
    """Parsed shape of one gsap.* call. Fields are nullable when the
    parser couldn't extract them from the source."""
    fn: str  # "from", "to", "fromTo"
    target_text: str  # raw target selector text — useful for class hints
    delay: float = 0.0  # when the animation starts (seconds from shot start)
    duration: float = 0.4
    stagger: float = 0.0
    from_props: Dict[str, str] = field(default_factory=dict)  # the "from" state
    to_props: Dict[str, str] = field(default_factory=dict)    # the "to" state


def _classify(call: _CallContext) -> Optional[Tuple[str, str, float]]:
    """Return (role, label, volume_mul) or None. None = no audible event."""
    fp = call.from_props
    tp = call.to_props
    target = call.target_text.lower()

    def _has(props: Dict[str, str], key: str) -> bool:
        return key in props

    def _num(props: Dict[str, str], key: str) -> Optional[float]:
        v = props.get(key)
        if v is None:
            return None
        try:
            return float(v)
        except (TypeError, ValueError):
            return None

    # Counter / number readout — target contains "counter", "count", "num",
    # "stat", or the from-prop has `textContent`. Mechanical tick stream.
    if any(k in target for k in ("counter", "count-", "countup", "stat-",
                                  "num-", "-num", "score", "tally")):
        return ("data_reveal", "counter_tick", 0.55)
    if "textcontent" in (fp.get("textContent", "") + tp.get("textContent", "")).lower():
        return ("data_reveal", "counter_tick", 0.55)

    # SplitText / per-char reveal — large stagger × stagger small (<0.08s)
    # means typewriter-clattering. We collapse into one event covering the
    # full duration.
    if 0 < call.stagger <= 0.08 and call.duration <= 0.6:
        # Typewriter / fast char reveal.
        if any(k in target for k in ("chars", "char-", "splittext", "letter",
                                      "word-", "title", "headline", "text-")):
            return ("ui_click", "typewriter", 0.50)

    # Bar / chart grow — height or width animation. Tonal sweep.
    if _has(tp, "height") or _has(tp, "width") or _has(fp, "scaleY") or _has(fp, "scaleX"):
        # Distinguish a bar grow (no opacity change, height animates) from
        # a generic resize. Bars target classes like "bar", "col", "fill".
        if (_has(tp, "height") or _has(fp, "scaleY")
                or any(k in target for k in ("bar", "col", "fill", "progress", "graph"))):
            return ("data_reveal", "bar_grow", 0.55)

    # SVG stroke draw (underline, annotation, marker). Targets `path` or
    # has `strokeDashoffset` / `drawSVG`.
    if ("path" in target or "underline" in target or "annot" in target
            or _has(tp, "strokeDashoffset") or _has(tp, "drawSVG")
            or _has(fp, "drawSVG")):
        return ("ui_chime", "underline_draw", 0.50)

    # Scale-in pop (no opacity, scale 0→1 or large→1)
    if _has(fp, "scale") and not _has(fp, "opacity"):
        from_scale = _num(fp, "scale")
        to_scale = _num(tp, "scale") if _has(tp, "scale") else 1.0
        if from_scale is not None and from_scale != 1.0:
            # Pop-in event.
            return ("ui_positive", "pop_in", 0.55)

    # Scale pulse with yoyo (a button being highlighted, badge pulsing)
    if _has(tp, "scale") and ("yoyo" in str(tp.get("yoyo", "")).lower()
                              or "repeat" in tp):
        return ("ui_click", "pulse", 0.45)

    # Stagger-medium reveal (list items, bullets). Soft chime.
    if 0.1 <= call.stagger <= 0.4 and (_has(fp, "opacity") or _has(fp, "y")
                                         or _has(fp, "x")):
        # List/bullet reveal — gentle.
        if any(k in target for k in ("item", "bullet", "list", "step",
                                      "card", "tile", "row", "child")):
            return ("ui_chime", "list_reveal", 0.50)

    # Slide-in (y or x from non-zero) — element entering frame
    if (_has(fp, "y") and not _has(fp, "scale")) or (_has(fp, "x") and not _has(fp, "scale")):
        # Soft swoosh-like reveal.
        return ("ui_chime", "slide_in", 0.45)

    # Fade-in alone (opacity 0 → 1, nothing else moves)
    if _has(fp, "opacity") and not (_has(fp, "y") or _has(fp, "x") or _has(fp, "scale")):
        # Only sound a fade when the duration is short and the target
        # looks like a meaningful element (button, badge, callout).
        # Generic background fades stay silent.
        if call.duration <= 0.7 and any(
            k in target for k in ("button", "cta", "badge", "callout",
                                   "highlight", "icon", "chip", "tag")
        ):
            return ("ui_chime", "element_appear", 0.45)
        return None

    return None


# ─────────────────────────────────────────────────────────────────────
# JS source extraction
# ─────────────────────────────────────────────────────────────────────

_SCRIPT_BLOCK_RE = re.compile(
    r"<script\b[^>]*>(.*?)</script>",
    re.DOTALL | re.IGNORECASE,
)


def _extract_script_blocks(html: str) -> List[str]:
    if not html:
        return []
    return _SCRIPT_BLOCK_RE.findall(html)


# Match `gsap.from(...)`, `gsap.to(...)`, `gsap.fromTo(...)`. Greedy on
# the argument list, then we balance-parse the parens manually because
# GSAP calls often contain nested object literals.
_GSAP_CALL_RE = re.compile(
    r"\bgsap\s*\.\s*(from|fromTo|to)\s*\(",
    re.IGNORECASE,
)


def _find_gsap_calls(js: str) -> List[Tuple[str, int, int]]:
    """Return [(fn, arg_start, arg_end), ...] for each balanced gsap call."""
    out: List[Tuple[str, int, int]] = []
    for m in _GSAP_CALL_RE.finditer(js):
        fn = m.group(1).lower()
        start = m.end()  # position right after the opening '('
        depth = 1
        i = start
        in_str: Optional[str] = None
        escape = False
        while i < len(js) and depth > 0:
            ch = js[i]
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif in_str:
                if ch == in_str:
                    in_str = None
            elif ch in ('"', "'", "`"):
                in_str = ch
            elif ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        if depth == 0 and i > start:
            out.append((fn, start, i))
    return out


def _split_top_level_args(args_text: str) -> List[str]:
    """Split a comma-separated argument list at top level (respecting nested
    parens, brackets, braces, and string literals)."""
    parts: List[str] = []
    depth = 0
    in_str: Optional[str] = None
    escape = False
    last = 0
    for i, ch in enumerate(args_text):
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if in_str:
            if ch == in_str:
                in_str = None
            continue
        if ch in ('"', "'", "`"):
            in_str = ch
            continue
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append(args_text[last:i])
            last = i + 1
    parts.append(args_text[last:])
    return [p.strip() for p in parts]


# Pull `{...}` object literals into a flat key→raw-value dict. We don't
# parse JS expressions; we just snapshot the right-hand side as text and
# let the classifier inspect it heuristically.
_OBJ_KV_RE = re.compile(
    r"""
    (?P<key>[A-Za-z_$][\w$]*)       # identifier key
    \s*:\s*
    (?P<val>
        '[^'\\]*(?:\\.[^'\\]*)*'    # single-quoted string
        |"[^"\\]*(?:\\.[^"\\]*)*"   # double-quoted string
        |`[^`\\]*(?:\\.[^`\\]*)*`   # template literal
        |\{[^}]*\}                  # nested object (shallow)
        |\[[^\]]*\]                 # array literal
        |[^,}]+                     # bare value
    )
    """,
    re.VERBOSE,
)


def _parse_object_literal(text: str) -> Dict[str, str]:
    """text is a snippet that starts with `{` and ends with `}`. Return
    a dict of key → raw-value (still as JS source, comments stripped)."""
    text = text.strip()
    if not text.startswith("{") or not text.endswith("}"):
        return {}
    inner = text[1:-1]
    # Strip /* */ and // comments to avoid confusing the regex.
    inner = re.sub(r"/\*.*?\*/", "", inner, flags=re.DOTALL)
    inner = re.sub(r"//[^\n]*", "", inner)
    out: Dict[str, str] = {}
    for m in _OBJ_KV_RE.finditer(inner):
        k = m.group("key")
        v = m.group("val").strip().rstrip(",").strip()
        # Strip surrounding quotes from string values so callers can compare
        # to plain text (e.g. ease: 'power2.out').
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"', "`"):
            v = v[1:-1]
        out[k] = v
    return out


_ARITH_EXPR_RE = re.compile(
    r"""^
    \s*
    (?P<base>-?\d+(?:\.\d+)?)
    \s*
    (?:                              # optional arithmetic terms
      (?P<op>[+\-*/])
      \s*
      (?:
        # numeric constant (with optional variable multiplier later)
        (?P<rhs_num>-?\d+(?:\.\d+)?)
        # optional `*var` or `/var` — we treat the variable as 0 since
        # this is the i=0 (first iteration) instance of the loop. That
        # gives us the FIRST event's time, which is the best-effort
        # estimate when the expression depends on a loop index.
        (?:\s*[*/]\s*[A-Za-z_$][\w$]*)?
        |
        # leading-variable form: `i*0.1` — drop the var (i=0) → 0.
        (?P<var_first>[A-Za-z_$][\w$]*)
        \s*[*/]\s*
        (?P<rhs_num2>-?\d+(?:\.\d+)?)
      )
    )?
    \s*$
    """,
    re.VERBOSE,
)


def _parse_number_literal(text: str) -> Optional[float]:
    """Parse a numeric expression to a float.

    Tier 1: plain number → `float(t)`.
    Tier 2: simple arithmetic like `0.3+i*0.1` or `0.2 + 0.1*idx` —
        treat the loop variable as 0 (representing the FIRST iteration)
        so a forEach-loop with `delay: 0.3+i*0.1` returns 0.3 (the time
        of the first event). This is a best-effort heuristic; collapsing
        the loop to a single event-at-start is preferable to all events
        landing at t=0 which is what the previous plain-`float()` did.

    Returns None when the expression isn't recognizable so the classifier
    falls back to its default (`delay=0` or `duration=0.4`)."""
    t = text.strip().rstrip(",").strip()
    if not t:
        return None
    # Tier 1: bare number.
    try:
        return float(t)
    except ValueError:
        pass
    # Tier 2: simple two-term arithmetic.
    m = _ARITH_EXPR_RE.match(t)
    if not m:
        return None
    try:
        base = float(m.group("base"))
    except (TypeError, ValueError):
        return None
    op = m.group("op")
    if not op:
        return base
    # Resolve right-hand side. var_first means `var * num` — treat var=0.
    if m.group("var_first") is not None:
        rhs = 0.0  # var=0 → entire term is 0
    else:
        try:
            rhs_num = m.group("rhs_num")
            rhs = float(rhs_num) if rhs_num is not None else 0.0
        except (TypeError, ValueError):
            return None
    # Apply the operator.
    if op == "+":
        return base + rhs
    if op == "-":
        return base - rhs
    if op == "*":
        return base * rhs
    if op == "/":
        return (base / rhs) if rhs else base
    return None


# ─────────────────────────────────────────────────────────────────────
# Per-call parse
# ─────────────────────────────────────────────────────────────────────

def _parse_call(fn: str, args_text: str) -> Optional[_CallContext]:
    """Build a _CallContext from one gsap.<fn>(args_text). Returns None
    if the call doesn't fit the expected `target, opts` shape."""
    parts = _split_top_level_args(args_text)
    if not parts:
        return None
    target_text = parts[0]

    if fn == "fromto":
        if len(parts) < 3:
            return None
        from_obj = _parse_object_literal(parts[1])
        to_obj = _parse_object_literal(parts[2])
    elif fn == "from":
        if len(parts) < 2:
            return None
        from_obj = _parse_object_literal(parts[1])
        # In .from, the "to" state is the element's pre-animation state
        # (i.e. the rendered defaults). We don't know those, so leave empty.
        to_obj = {}
    elif fn == "to":
        if len(parts) < 2:
            return None
        from_obj = {}
        to_obj = _parse_object_literal(parts[1])
    else:
        return None

    # Common timing fields live in the LAST options object — for fromTo
    # that's the third arg (to_obj); for from/to it's the second arg.
    timing_src = to_obj if fn in ("fromto", "to") else from_obj
    delay = _parse_number_literal(timing_src.get("delay", "0")) or 0.0
    duration = _parse_number_literal(timing_src.get("duration", "0.4")) or 0.4
    stagger = _parse_number_literal(timing_src.get("stagger", "0")) or 0.0

    return _CallContext(
        fn=fn,
        target_text=target_text,
        delay=max(0.0, delay),
        duration=max(0.01, duration),
        stagger=max(0.0, stagger),
        from_props=from_obj,
        to_props=to_obj,
    )


# ─────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────

# Two events within this distance get collapsed (we keep the higher
# volume_mul). Prevents flood when the LLM emits multiple near-identical
# tweens for the same element.
_MIN_EVENT_GAP_S = 0.30


def scan_events(
    html: str,
    shot_duration_s: float = 999.0,
    *,
    max_events: int = 6,
) -> List[Dict[str, Any]]:
    """Walk the shot's HTML, find all gsap.* calls, classify them, and
    return a list of SFX-worthy events (each a plain dict suitable for
    direct attachment to `entry["_sfx_events"]`).

    `shot_duration_s` clamps events past the shot's end (occasionally
    GSAP delays exceed the shot duration when the LLM overshoots —
    those events would never play anyway).
    `max_events` is a per-shot ceiling. After classification + collapse,
    keep the highest-volume_mul events up to this cap. Tuned for "≤ 6
    audible moments per shot" as a sanity ceiling.
    """
    if not html:
        return []

    raw_events: List[GsapEvent] = []
    for block in _extract_script_blocks(html):
        for fn, a, b in _find_gsap_calls(block):
            args = block[a:b]
            ctx = _parse_call(fn, args)
            if ctx is None:
                continue
            classified = _classify(ctx)
            if classified is None:
                continue
            role, label, vol = classified
            t = ctx.delay
            if t > shot_duration_s + 0.5:
                continue  # past shot end — would never play
            raw_events.append(GsapEvent(
                t=t, role=role, label=label,
                volume_mul=vol, duration=ctx.duration,
            ))

    if not raw_events:
        return []

    # Time-sort + collapse near-duplicates within _MIN_EVENT_GAP_S.
    raw_events.sort(key=lambda e: e.t)
    collapsed: List[GsapEvent] = [raw_events[0]]
    for ev in raw_events[1:]:
        prev = collapsed[-1]
        if ev.t - prev.t < _MIN_EVENT_GAP_S and ev.role == prev.role:
            # Same role, same window — keep the one with higher volume.
            if ev.volume_mul > prev.volume_mul:
                collapsed[-1] = ev
            continue
        collapsed.append(ev)

    # Cap to max_events; prefer punchier (higher volume_mul).
    if len(collapsed) > max_events:
        collapsed.sort(key=lambda e: e.volume_mul, reverse=True)
        collapsed = collapsed[:max_events]
        collapsed.sort(key=lambda e: e.t)

    return [e.as_dict() for e in collapsed]
