"""Incident code → {category, subcategory} mapping.

Ported verbatim from media_service LL_AI_Constant.INCIDENT_TYPES. Serialized to
JSON and embedded in the incident-structure prompt (the LLM must pick an
event_code from this exact mapping). Keep in sync with the Java source if it
changes.
"""
from __future__ import annotations

import json
from typing import Dict

INCIDENT_TYPES: Dict[str, Dict[str, str]] = {
    "GD0003": {"category": "APPRAISAL BY CLIENT", "subcategory": "Verbal"},
    "GD0001": {"category": "APPRAISAL BY SUPERVISOR", "subcategory": "Verbal"},
    "GD0002": {"category": "APPRAISAL BY SUPERVISOR", "subcategory": "Written"},
    "GD0004": {"category": "APPRAISAL BY CLIENT", "subcategory": "Written"},
    "GD0005": {"category": "APPRAISAL BY MANAGEMENT", "subcategory": "Written"},
    "TFT1001": {"category": "THEFT", "subcategory": "Livestock"},
    "TFT1002": {"category": "THEFT", "subcategory": "Theft of Wildlife (poaching)"},
    "BGY1002": {"category": "BURGLARY", "subcategory": "Burglary at business"},
    "CC1002": {"category": "CYBER CRIME", "subcategory": "Data Breaches in Farming Communities"},
    "CC1001": {"category": "CYBER CRIME", "subcategory": "Hacking of Agricultural Systems"},
    "CAA1001": {"category": "CRIMES AGAINST ANIMALS", "subcategory": "Cruelty to animals"},
    "LII1001": {"category": "LAND INVASION AND INTRUSION", "subcategory": "Unauthorized Occupation of Farmland"},
    "LA1001": {"category": "LABOUR ACTION", "subcategory": "Peaceful protest (picketing, strike)"},
    "CIG1005": {"category": "CRIMES IN GENERAL", "subcategory": "Liquor act offences"},
    "TF1002": {"category": "EMPLOYEE THEFT AND FRAUD", "subcategory": "Falsifying Documents"},
    "AT1002": {"category": "ABSENTEEISM AND TARDINESS", "subcategory": "Chronic Tardiness"},
    "TF1003": {"category": "EMPLOYEE THEFT AND FRAUD", "subcategory": "Theft of Company Property"},
    "DH1000": {"category": "DISCRIMINATION AND HARASSMENT", "subcategory": "Sexual Harassment"},
    "SV1001": {"category": "SAFETY VIOLATIONS", "subcategory": "Ignoring Safety Procedures"},
    "SV1002": {"category": "SAFETY VIOLATIONS", "subcategory": "Failure to Use Protective Equipment"},
    "SV1003": {"category": "SAFETY VIOLATIONS", "subcategory": "Negligence Leading to Accidents"},
    "DH1002": {"category": "DISCRIMINATION AND HARASSMENT", "subcategory": "Gender Discrimination"},
    "DH1003": {"category": "DISCRIMINATION AND HARASSMENT", "subcategory": "Age Discrimination"},
    "DH1004": {"category": "DISCRIMINATION AND HARASSMENT", "subcategory": "Disability Discrimination"},
    "BI1002": {"category": "BULLYING", "subcategory": "Physical Intimidation"},
    "DH1001": {"category": "DISCRIMINATION AND HARASSMENT", "subcategory": "Racial Discrimination"},
    "TF1001": {"category": "EMPLOYEE THEFT AND FRAUD", "subcategory": "Embezzlement"},
    "BI1003": {"category": "BULLYING", "subcategory": "Cyberbullying"},
    "ELC1005": {"category": "ENVIRONMENTAL CRIMES", "subcategory": "Pollution of Agricultural Areas"},
    "IE1001": {"category": "INDUSTRIAL ESPIONAGE", "subcategory": "Unauthorized Access to Competitors' Information"},
    "IT1001": {"category": "INSIDER TRADING", "subcategory": "Illegally Trading Company Securities Based on Non-Public Information"},
    "CI1001": {"category": "CONFLICT OF INTEREST", "subcategory": "Engaging in Activities that Compromise Objectivity"},
    "SG1001": {"category": "SABOTAGE", "subcategory": "Intentional Damage to Company Property"},
    "SG1002": {"category": "SABOTAGE", "subcategory": "Disruptive Actions Affecting Operations"},
    "VP1001": {"category": "VIOLATION OF COMPANY POLICIES", "subcategory": "Breach of Confidentiality"},
    "VP1002": {"category": "VIOLATION OF COMPANY POLICIES", "subcategory": "Misuse of Company Resources"},
    "VP1003": {"category": "VIOLATION OF COMPANY POLICIES", "subcategory": "Violation of Social Media Policies"},
    "FC1002": {"category": "FALSE CLAIMS", "subcategory": "Submitting False Invoices or Reports"},
    "CI1002": {"category": "CONFLICT OF INTEREST", "subcategory": "Accepting Bribes or Kickbacks"},
    "WR1001": {"category": "WHISTLEBLOWER RETALIATION", "subcategory": "Intimidation, harassment, threaten, assault whistleblowers"},
    "NR1001": {"category": "NON-COMPLIANCE WITH REGULATIONS", "subcategory": "Violating Industry Standards"},
    "FC1001": {"category": "FALSE CLAIMS", "subcategory": "Providing False Information to Clients or Customers"},
    "SA1002": {"category": "SUSPICIOUS ACTIVITY", "subcategory": "Tracks found"},
    "UP1001": {"category": "UNETHICAL NEGOTIATION PRACTICES", "subcategory": "Bribery in Business Deals"},
    "UP1002": {"category": "UNETHICAL NEGOTIATION PRACTICES", "subcategory": "Unfair Business Practices"},
    "UP1003": {"category": "UNETHICAL NEGOTIATION PRACTICES", "subcategory": "Sharing Confidential Information with External Parties"},
    "MI1001": {"category": "MISUSE OF COMPANY INFORMATION", "subcategory": "Exploiting Inside Information for Personal Gain"},
    "LV1002": {"category": "LABOR UNION VIOLATIONS", "subcategory": "Interfering with Union Activities"},
    "LV1003": {"category": "LABOR UNION VIOLATIONS", "subcategory": "Retaliating Against Union Members"},
    "ID1002": {"category": "INSUBORDINATION", "subcategory": "Disregarding Company Policies"},
    "IE1002": {"category": "INDUSTRIAL ESPIONAGE", "subcategory": "Stealing Trade Secrets"},
    "BI1001": {"category": "BULLYING", "subcategory": "Verbal Abuse"},
    "AT1001": {"category": "ABSENTEEISM AND TARDINESS", "subcategory": "Excessive Absenteeism"},
    "NR1002": {"category": "NON-COMPLIANCE WITH REGULATIONS", "subcategory": "Ignoring Government Regulations"},
    "LV1001": {"category": "LABOR UNION VIOLATIONS", "subcategory": "Scouting for Labour unions"},
    "ID1001": {"category": "INSUBORDINATION", "subcategory": "Refusing to Follow Supervisory Instructions"},
    "TFT1003": {"category": "THEFT", "subcategory": "Theft of Agricultural Produce"},
    "TFT1004": {"category": "THEFT", "subcategory": "Theft General"},
    "TFT1005": {"category": "THEFT", "subcategory": "Theft of registered self-propelling vehicles"},
    "TFT1006": {"category": "THEFT", "subcategory": "Theft out or from vehicle"},
    "TFT1007": {"category": "THEFT", "subcategory": "Theft of implements"},
    "TFT1008": {"category": "THEFT", "subcategory": "Theft of tools"},
    "TFT1009": {"category": "THEFT", "subcategory": "Theft of pump equipment"},
    "TFT1010": {"category": "THEFT", "subcategory": "Theft of cables"},
    "TFT1011": {"category": "THEFT", "subcategory": "Theft of solar equipment"},
    "TFT1012": {"category": "THEFT", "subcategory": "Theft of cash"},
    "RBY1001": {"category": "ROBBERY", "subcategory": "Robbery at residence (farm house, guest house, room, other)"},
    "RBY1002": {"category": "ROBBERY", "subcategory": "Robbery at business (factory, production area, office, storage area, other)"},
    "RBY1003": {"category": "ROBBERY", "subcategory": "Robbery of motorvehicle (carjacking)"},
    "RBY1004": {"category": "ROBBERY", "subcategory": "Robbery Other (person robbed outside residence or business)"},
    "BGY1001": {"category": "BURGLARY", "subcategory": "Burglary at residence"},
    "FD1001": {"category": "FRAUD", "subcategory": "Committed by customer, supplier, contractor"},
    "FD1002": {"category": "FRAUD", "subcategory": "Committed by employee"},
    "CAP1001": {"category": "CRIMES AGAINST PERSONS", "subcategory": "Murder"},
    "CAP1002": {"category": "CRIMES AGAINST PERSONS", "subcategory": "Assault"},
    "CAP1003": {"category": "CRIMES AGAINST PERSONS", "subcategory": "Sexual offences"},
    "CAP1004": {"category": "CRIMES AGAINST PERSONS", "subcategory": "Kidnapping (adult person taken against will by force for ransom or extortion)"},
    "CAP1005": {"category": "CRIMES AGAINST PERSONS", "subcategory": "Abduction (minor person / child taken willingly or unwillingly from lawful guardian)"},
    "ELC1006": {"category": "ENVIRONMENTAL CRIMES", "subcategory": "Illegal Mining on Agricultural Land"},
    "CAP1006": {"category": "CRIMES AGAINST PERSONS", "subcategory": "Hostage situation at the workplace (movement of person deliberately restricted against threats and demands)"},
    "COP1001": {"category": "CRIMES AGAINST PROPERTY", "subcategory": "Arson (setting fire to buildings and built structures)"},
    "COP1002": {"category": "CRIMES AGAINST PROPERTY", "subcategory": "Veld Fire (illegally setting veld and bush on fire)"},
    "COP1003": {"category": "CRIMES AGAINST PROPERTY", "subcategory": "Destruction of crops"},
    "COP1004": {"category": "CRIMES AGAINST PROPERTY", "subcategory": "Damaging Fences and Boundaries"},
    "COP1005": {"category": "CRIMES AGAINST PROPERTY", "subcategory": "Damaging Farm Infrastructure"},
    "CAA1002": {"category": "CRIMES AGAINST ANIMALS", "subcategory": "Livestock disease sabotage"},
    "LII1002": {"category": "LAND INVASION AND INTRUSION", "subcategory": "Person illegally trespassing / intruding / enroaching on private property."},
    "LII1003": {"category": "LAND INVASION AND INTRUSION", "subcategory": "Livestock intruding onto private property."},
    "LII1004": {"category": "LAND INVASION AND INTRUSION", "subcategory": "Illegal grazing on agricultural land."},
    "LII1005": {"category": "LAND INVASION AND INTRUSION", "subcategory": "Unauthorized Hunting Activities"},
    "AAD1001": {"category": "ACCIDENTS AND DISASTERS", "subcategory": "Natural disaster"},
    "AAD1002": {"category": "ACCIDENTS AND DISASTERS", "subcategory": "Industrial accident"},
    "AAD1003": {"category": "ACCIDENTS AND DISASTERS", "subcategory": "Transport accident"},
    "ELC1001": {"category": "ENVIRONMENTAL CRIMES", "subcategory": "Unauthorized Access to Water Sources"},
    "ELC1002": {"category": "ENVIRONMENTAL CRIMES", "subcategory": "Unauthorized Access to Electricity Sources"},
    "ELC1003": {"category": "ENVIRONMENTAL CRIMES", "subcategory": "Diverting Water Illegally"},
    "ELC1004": {"category": "ENVIRONMENTAL CRIMES", "subcategory": "Illegal Dumping on Farmland"},
    "ELC1007": {"category": "ENVIRONMENTAL CRIMES", "subcategory": "Environmental Degradation from Mining"},
    "LA1002": {"category": "LABOUR ACTION", "subcategory": "Violent protest (property damage, injury to persons)"},
    "LA1003": {"category": "LABOUR ACTION", "subcategory": "Intimidation (preventing willing employees from working)"},
    "CIG1001": {"category": "CRIMES IN GENERAL", "subcategory": "Disturbing of the peace"},
    "CIG1002": {"category": "CRIMES IN GENERAL", "subcategory": "Illegal Possession of Firearms"},
    "CIG1003": {"category": "CRIMES IN GENERAL", "subcategory": "Firearms Control Act Offences"},
    "CIG1004": {"category": "CRIMES IN GENERAL", "subcategory": "Illegal Possesion of drugs"},
    "CIG1006": {"category": "CRIMES IN GENERAL", "subcategory": "Illegal Trade in Agricultural Produce"},
    "ET1001": {"category": "EXTERNAL THREATS", "subcategory": "Inter-community Disputes Impacting Farming Operations"},
    "ET1002": {"category": "EXTERNAL THREATS", "subcategory": "Tribal or Ethnic Conflicts"},
    "ET1003": {"category": "EXTERNAL THREATS", "subcategory": "Crimes Perpetrated Across International Borders"},
    "ET1004": {"category": "EXTERNAL THREATS", "subcategory": "Transnational Criminal Activities in Farming Regions"},
    "ET1005": {"category": "EXTERNAL THREATS", "subcategory": "Human Trafficking in Farming Communities"},
    "SA1001": {"category": "SUSPICIOUS ACTIVITY", "subcategory": "Shots fired"},
    "SA1003": {"category": "SUSPICIOUS ACTIVITY", "subcategory": "Snares found (no animal trapped)"},
    "SA1004": {"category": "SUSPICIOUS ACTIVITY", "subcategory": "Suspicious persons moving inside or outside of the site"},
    "SA1005": {"category": "SUSPICIOUS ACTIVITY", "subcategory": "Tampering with fences, locks, equipment"},
    "SA1006": {"category": "SUSPICIOUS ACTIVITY", "subcategory": "Other"},
}


def incident_types_json() -> str:
    """JSON string of the mapping, as embedded in the prompt (mirrors Java
    ObjectMapper.writeValueAsString(LL_AI_Constant.getIncidentTypes()))."""
    return json.dumps(INCIDENT_TYPES)
