package vacademy.io.admin_core_service.features.learner_credentials.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import vacademy.io.admin_core_service.features.auth_service.service.AuthService;
import vacademy.io.admin_core_service.features.learner.service.LearnerPortalAccessService;
import vacademy.io.admin_core_service.features.learner_credentials.dto.LearnerCredentialSendResult;
import vacademy.io.admin_core_service.features.learner_credentials.dto.PasswordResetLinkDTO;
import vacademy.io.admin_core_service.features.learner_credentials.enums.CredentialDeliveryMode;
import vacademy.io.admin_core_service.features.notification.enums.NotificationEventType;
import vacademy.io.admin_core_service.features.notification.enums.NotificationTemplateType;
import vacademy.io.admin_core_service.features.notification.service.DynamicNotificationService;
import vacademy.io.admin_core_service.features.notification.service.NotificationTemplateBindingService;
import vacademy.io.admin_core_service.features.parent_link.dto.CredentialTemplateConfigDTO;
import vacademy.io.common.auth.dto.UserCredentials;
import vacademy.io.common.auth.dto.UserDTO;
import vacademy.io.common.exceptions.VacademyException;

import java.util.ArrayList;
import java.util.List;

/**
 * The "Send Reset Password Email" action behind a learner's Portal Access panel, and the
 * template binding that decides what that email looks like.
 *
 * <h3>Why there are two modes</h3>
 * The original action had exactly one behaviour: mail the learner their existing username and
 * password from a hardcoded body in auth_service. That is still the right default for institutes
 * who have not authored anything, so it stays untouched as {@link CredentialDeliveryMode#DEFAULT},
 * workflow trigger and all.
 *
 * <p>{@link CredentialDeliveryMode#TEMPLATE} sends the institute's own email instead, built around
 * a reset-password link that opens the learner portal login with their username already filled in
 * and hands off to the existing update-profile screen, where they choose a new password. That is a
 * materially different message: it never puts a plaintext password in an inbox.
 *
 * <p>The link is intentionally shaped so it can be generated by something that is not us. An admin
 * can copy {@link PasswordResetLinkDTO#getResetLinkTemplate()} into a third-party system, which
 * substitutes its own usernames and gets working links without calling this service at all.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class LearnerPasswordResetService {

    private final AuthService authService;
    private final LearnerPortalAccessService learnerPortalAccessService;
    private final DynamicNotificationService dynamicNotificationService;
    private final NotificationTemplateBindingService templateBindingService;

    /** Placeholder left in {@link PasswordResetLinkDTO#getResetLinkTemplate()} for integrators. */
    private static final String USERNAME_PLACEHOLDER = "{username}";

    /**
     * The reset link for one learner, plus the templated form for third-party integrators.
     *
     * <p>Resolved per learner rather than per institute because the portal host is too: a learner
     * in a sub-org with its own branded portal must be sent to that host, not the parent's.
     */
    public PasswordResetLinkDTO getResetLink(String instituteId, String userId) {
        if (!StringUtils.hasText(instituteId) || !StringUtils.hasText(userId)) {
            throw new VacademyException("instituteId and userId are required");
        }
        String username = resolveUsername(userId);
        return PasswordResetLinkDTO.builder()
                .username(username)
                .resetLink(learnerPortalAccessService.buildPasswordResetLink(instituteId, userId, username))
                .resetLinkTemplate(learnerPortalAccessService.buildPasswordResetLinkTemplate(instituteId, userId))
                .usernamePlaceholder(USERNAME_PLACEHOLDER)
                .build();
    }

    /**
     * Sends the reset mail on each requested channel.
     *
     * @param packageId  only consulted in DEFAULT mode, where an institute may have a workflow
     *                   bound to the send; ignored by the template path
     * @param mode       DEFAULT keeps the platform's built-in mail, TEMPLATE renders the institute's
     * @param templateId optional one-off template for this send; when absent TEMPLATE mode uses the
     *                   institute's standing binding
     * @param channels   EMAIL and/or WHATSAPP; DEFAULT mode is email-only and says so
     */
    public LearnerCredentialSendResult send(String instituteId, String userId, String packageId,
                                            CredentialDeliveryMode mode, String templateId,
                                            List<NotificationTemplateType> channels) {
        if (!StringUtils.hasText(instituteId) || !StringUtils.hasText(userId)) {
            throw new VacademyException("instituteId and userId are required");
        }
        CredentialDeliveryMode resolvedMode = mode != null ? mode : CredentialDeliveryMode.DEFAULT;

        if (resolvedMode == CredentialDeliveryMode.DEFAULT) {
            // Unchanged legacy path, workflow trigger included: an institute that has wired
            // SEND_LEARNER_CREDENTIALS to its own LMS must keep getting that, not a template.
            boolean sent = Boolean.TRUE.equals(
                    learnerPortalAccessService.sendCredForLMS(instituteId, packageId, userId));
            return LearnerCredentialSendResult.builder()
                    .sentChannels(sent ? List.of(NotificationTemplateType.EMAIL.name()) : List.of())
                    .skippedChannels(sent ? List.of() : List.of(NotificationTemplateType.EMAIL.name()))
                    .message(sent
                            ? "Sent using the system default email."
                            : "Nothing was sent. The learner may have no email address on file.")
                    .build();
        }

        List<NotificationTemplateType> resolvedChannels =
                (channels == null || channels.isEmpty()) ? List.of(NotificationTemplateType.EMAIL) : channels;

        UserDTO learner = authService.getUsersFromAuthServiceByUserIds(List.of(userId))
                .stream().findFirst()
                .orElseThrow(() -> new VacademyException("User not found: " + userId));

        String username = resolveUsername(userId);
        String resetLink = learnerPortalAccessService.buildPasswordResetLink(instituteId, userId, username);
        String resetLinkTemplate = learnerPortalAccessService.buildPasswordResetLinkTemplate(instituteId, userId);

        List<String> sent = new ArrayList<>();
        List<String> skipped = new ArrayList<>();
        for (NotificationTemplateType channel : resolvedChannels) {
            boolean dispatched = dynamicNotificationService.sendLearnerPasswordResetNotification(
                    instituteId, channel, learner, username, resetLink, resetLinkTemplate, templateId);
            (dispatched ? sent : skipped).add(channel.name());
        }

        return LearnerCredentialSendResult.builder()
                .sentChannels(sent)
                .skippedChannels(skipped)
                .message(buildMessage(sent, skipped))
                .build();
    }

    /** The template currently bound to the password-reset mail for this institute + channel. */
    public CredentialTemplateConfigDTO getTemplateConfig(String instituteId, NotificationTemplateType channel) {
        return templateBindingService.get(NotificationEventType.LEARNER_PASSWORD_RESET, instituteId, channel);
    }

    public void setTemplate(String instituteId, NotificationTemplateType channel, String templateId) {
        templateBindingService.set(NotificationEventType.LEARNER_PASSWORD_RESET, instituteId, channel, templateId);
    }

    public void clearTemplate(String instituteId, NotificationTemplateType channel) {
        templateBindingService.clear(NotificationEventType.LEARNER_PASSWORD_RESET, instituteId, channel);
    }

    /**
     * The learner's login username, read from auth_service rather than taken from the request:
     * it is the authoritative copy, and a link built from a stale username silently fails to
     * pre-fill for the one person who needs it to.
     */
    private String resolveUsername(String userId) {
        UserCredentials credentials = authService.getUsersCredentials(List.of(userId))
                .stream().findFirst()
                .orElseThrow(() -> new VacademyException("Credentials not found for user: " + userId));
        return credentials.getUsername();
    }

    private String buildMessage(List<String> sent, List<String> skipped) {
        if (sent.isEmpty()) {
            return "Nothing was sent. Select a password-reset template for this channel, "
                    + "and check the learner has the contact detail it needs.";
        }
        if (skipped.isEmpty()) {
            return "Password reset link sent on " + String.join(", ", sent) + ".";
        }
        return "Password reset link sent on " + String.join(", ", sent)
                + ". Skipped " + String.join(", ", skipped)
                + " (no template selected, or the learner has no contact detail for it).";
    }
}
