import { useState } from 'react';
import { initiateStudentAnalysis } from '@/services/student-analysis';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import { useStudentSidebar } from '../../../../-context/selected-student-sidebar-context';
import { MyDialog } from '@/components/design-system/dialog';
import { MyButton } from '@/components/design-system/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { getTerminology } from '@/components/common/layout-container/sidebar/utils';
import { RoleTerms, SystemTerms } from '@/routes/settings/-components/NamingSettings';

interface InitiateReportDialogProps {
    onSuccess?: () => void;
}

/** Admin-selectable report module keys. Must match the backend ReportModule keys. */
const MODULE_KEYS = [
    'attendance',
    'live_classes',
    'academics',
    'activity',
    'progress',
    'certificates',
    'assignments',
    'doubts',
    'login',
] as const;
const ALL_MODULE_KEYS: string[] = [...MODULE_KEYS];

/** Builds the display list (key = untranslated logic value, label = translated display text). */
const buildReportModules = (t: TFunction): { key: string; label: string }[] => [
    { key: 'attendance', label: t('moduleLabels.attendance') },
    { key: 'live_classes', label: t('moduleLabels.liveClasses') },
    { key: 'academics', label: t('moduleLabels.academics') },
    { key: 'activity', label: t('moduleLabels.activity') },
    { key: 'progress', label: t('moduleLabels.progress') },
    { key: 'certificates', label: t('moduleLabels.certificates') },
    { key: 'assignments', label: t('moduleLabels.assignments') },
    { key: 'doubts', label: t('moduleLabels.doubts') },
    { key: 'login', label: t('moduleLabels.login') },
];

export const InitiateReportDialog = ({ onSuccess }: InitiateReportDialogProps) => {
    const { t } = useTranslation('manageStudentsInitiateReportDialog');
    const [open, setOpen] = useState(false);
    const [reportName, setReportName] = useState('');
    const [sendEmail, setSendEmail] = useState(true);
    const [startDate, setStartDate] = useState('');
    const [endDate, setEndDate] = useState('');
    const [selectedModules, setSelectedModules] = useState<string[]>(ALL_MODULE_KEYS);
    const [loading, setLoading] = useState(false);
    const { selectedStudent } = useStudentSidebar();

    const reportModules = buildReportModules(t);

    const handleOpen = (nextOpen: boolean) => {
        setOpen(nextOpen);
        if (nextOpen) {
            // Reset to defaults each time the dialog opens
            setSelectedModules(ALL_MODULE_KEYS);
            setReportName('');
            setSendEmail(true);
        }
    };

    /** Live placeholder for the name field: "Report: <start> to <end>" */
    const namePlaceholder =
        startDate && endDate
            ? t('form.reportName.placeholder.withRange', { startDate, endDate })
            : startDate
              ? t('form.reportName.placeholder.startOnly', { startDate })
              : t('form.reportName.placeholder.autoGenerated');

    const toggleModule = (key: string) => {
        setSelectedModules((prev) =>
            prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]
        );
    };

    const handleInitiate = async () => {
        if (!selectedStudent?.user_id) return;
        if (!startDate || !endDate) {
            toast.error(t('validation.missingDates'));
            return;
        }
        // An inverted range makes every collector query an empty window, and the report comes back
        // as a confident 0% across the board. Catch it here rather than shipping a wrong report.
        if (startDate > endDate) {
            toast.error(t('validation.invalidRange'));
            return;
        }
        if (selectedModules.length === 0) {
            toast.error(t('validation.noModulesSelected'));
            return;
        }

        // Package/session is taken from the selected student (not shown in the form).
        const packageSessionId = (selectedStudent.package_session_id ?? '').trim();

        setLoading(true);
        try {
            const trimmedName = reportName.trim();
            const response = await initiateStudentAnalysis(
                {
                    user_id: selectedStudent.user_id,
                    start_date_iso: startDate,
                    end_date_iso: endDate,
                    report_version: 'v2',
                    send_email: sendEmail,
                    include_modules: selectedModules,
                    ...(trimmedName ? { name: trimmedName } : {}),
                    ...(packageSessionId
                        ? { batch_id: packageSessionId, package_session_id: packageSessionId }
                        : {}),
                },
                selectedStudent.institute_id
            );

            if (response.process_id) {
                const storedProcesses = JSON.parse(
                    sessionStorage.getItem('student_analysis_processes') || '[]'
                );
                storedProcesses.push(response.process_id);
                sessionStorage.setItem(
                    'student_analysis_processes',
                    JSON.stringify(storedProcesses)
                );

                toast.success(t('toast.success'));
                setOpen(false);
                onSuccess?.();
            } else {
                toast.error(response.message || t('toast.failure'));
            }
        } catch (error) {
            console.error('Error initiating analysis:', error);
            toast.error(t('toast.failure'));
        } finally {
            setLoading(false);
        }
    };

    return (
        <MyDialog
            open={open}
            onOpenChange={handleOpen}
            trigger={<MyButton>{t('trigger')}</MyButton>}
            heading={t('heading', {
                term: getTerminology(RoleTerms.Learner, SystemTerms.Learner),
            })}
            dialogWidth="max-w-sm"
            content={
                <div className="flex flex-col gap-4">
                    <p className="text-sm text-neutral-500">{t('description')}</p>
                    <div className="flex flex-col gap-4">
                        {/* Report Name (optional) */}
                        <div className="flex flex-col gap-1.5">
                            <Label
                                htmlFor="report-name"
                                className="text-xs font-medium text-neutral-600"
                            >
                                {t('form.reportName.label')}{' '}
                                <span className="font-normal text-neutral-400">
                                    {t('form.reportName.optional')}
                                </span>
                            </Label>
                            <Input
                                id="report-name"
                                type="text"
                                placeholder={namePlaceholder}
                                value={reportName}
                                onChange={(e) => setReportName(e.target.value)}
                            />
                        </div>

                        {/* Modules to include */}
                        <div className="flex flex-col gap-1.5">
                            <Label className="text-xs font-medium text-neutral-600">
                                {t('form.modules.label')}
                            </Label>
                            <p className="text-xs text-neutral-400">{t('form.modules.helper')}</p>
                            <div className="mt-1 grid grid-cols-2 gap-2">
                                {reportModules.map((m) => (
                                    <label
                                        key={m.key}
                                        htmlFor={`module-${m.key}`}
                                        className="flex cursor-pointer items-center gap-2 text-sm text-neutral-600"
                                    >
                                        <Checkbox
                                            id={`module-${m.key}`}
                                            checked={selectedModules.includes(m.key)}
                                            onCheckedChange={() => toggleModule(m.key)}
                                        />
                                        {m.label}
                                    </label>
                                ))}
                            </div>
                        </div>

                        {/* Start Date */}
                        <div className="flex flex-col gap-1.5">
                            <Label
                                htmlFor="start-date"
                                className="text-xs font-medium text-neutral-600"
                            >
                                {t('form.startDate.label')}
                            </Label>
                            <Input
                                id="start-date"
                                type="date"
                                value={startDate}
                                max={endDate || undefined}
                                onChange={(e) => setStartDate(e.target.value)}
                            />
                        </div>

                        {/* End Date */}
                        <div className="flex flex-col gap-1.5">
                            <Label
                                htmlFor="end-date"
                                className="text-xs font-medium text-neutral-600"
                            >
                                {t('form.endDate.label')}
                            </Label>
                            <Input
                                id="end-date"
                                type="date"
                                value={endDate}
                                min={startDate || undefined}
                                onChange={(e) => setEndDate(e.target.value)}
                            />
                        </div>

                        {/* Notify learner */}
                        <div className="flex flex-col gap-1.5">
                            <label
                                htmlFor="send-email"
                                className="flex cursor-pointer items-center gap-2 text-sm text-neutral-600"
                            >
                                <Checkbox
                                    id="send-email"
                                    checked={sendEmail}
                                    onCheckedChange={(c) => setSendEmail(c === true)}
                                />
                                {t('form.sendEmail.label')}
                            </label>
                            <p className="text-xs text-neutral-400">
                                {t('form.sendEmail.helper')}
                            </p>
                        </div>
                    </div>
                </div>
            }
            footer={
                <>
                    <MyButton
                        buttonType="secondary"
                        onClick={() => setOpen(false)}
                        disabled={loading}
                    >
                        {t('actions.cancel')}
                    </MyButton>
                    <MyButton onClick={handleInitiate} disabled={loading}>
                        {loading ? t('actions.initiating') : t('actions.generate')}
                    </MyButton>
                </>
            }
        />
    );
};
