package vacademy.io.admin_core_service.features.doubts.manager;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import vacademy.io.admin_core_service.features.institute.entity.Template;
import vacademy.io.admin_core_service.features.institute.repository.TemplateRepository;
import vacademy.io.common.institute.entity.Institute;

/**
 * Inserts the per-institute default doubt-notification email templates.
 *
 * <p>Called at institute creation time from
 * {@code InstituteSettingService.createDefaultSettingsForInstitute}. Mirror of
 * {@code V214__Seed_Doubt_Notification_Email_Templates.sql}, which handles institutes that
 * already existed at deploy time.
 *
 * <p>Template ids are auto-generated by Hibernate's {@code @UuidGenerator} on
 * {@link Template} — we never set them explicitly. Uniqueness is enforced on
 * {@code (institute_id, name)} via the existing index, which is also what we check for
 * idempotency. This matches the V214 migration's strategy.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class DoubtTemplateSeeder {

    private final TemplateRepository templateRepository;

    /** Seeds both default templates for the given institute. Safe to call repeatedly. */
    public void seedDefaults(Institute institute) {
        if (institute == null || institute.getId() == null || institute.getId().isEmpty()) return;
        try {
            seedOne(institute.getId(),
                    DoubtNotificationTemplateDefaults.RAISED_TEMPLATE_NAME,
                    DoubtNotificationTemplateDefaults.RAISED_SUBJECT,
                    DoubtNotificationTemplateDefaults.RAISED_HTML);
            seedOne(institute.getId(),
                    DoubtNotificationTemplateDefaults.RESOLVED_TEMPLATE_NAME,
                    DoubtNotificationTemplateDefaults.RESOLVED_SUBJECT,
                    DoubtNotificationTemplateDefaults.RESOLVED_HTML);
        } catch (Exception e) {
            // Never break institute creation on a template-seed failure.
            log.error("Failed to seed doubt notification templates for institute {}: {}",
                    institute.getId(), e.getMessage(), e);
        }
    }

    private void seedOne(String instituteId, String name, String subject, String content) {
        if (templateRepository.existsByInstituteIdAndName(instituteId, name)) {
            return;
        }
        // No explicit id — @UuidGenerator on Template.id fills it on persist.
        Template template = Template.builder()
                .type("EMAIL")
                .instituteId(instituteId)
                .name(name)
                .subject(subject)
                .content(content)
                .contentType("HTML")
                .settingJson("{\"email_type\":\"UTILITY_EMAIL\"}")
                .canDelete(true)
                .status("ACTIVE")
                .templateCategory("NOTIFICATION")
                .createdBy("system")
                .updatedBy("system")
                .build();
        Template saved = templateRepository.save(template);
        log.info("Seeded doubt notification template '{}' (id={}) for institute {}",
                name, saved.getId(), instituteId);
    }
}
