package vacademy.io.admin_core_service.features.fee_management.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import vacademy.io.admin_core_service.features.fee_management.dto.PayInstallmentsRequestDTO;
import vacademy.io.admin_core_service.features.fee_management.dto.StudentFeeAllocationLedgerDTO;
import vacademy.io.admin_core_service.features.fee_management.dto.StudentFeePaymentDTO;
import vacademy.io.admin_core_service.features.fee_management.service.FeeTrackingService;
import vacademy.io.admin_core_service.features.fee_management.service.LearnerInstallmentPaymentService;
import vacademy.io.common.auth.model.CustomUserDetails;
import vacademy.io.common.payment.dto.PaymentResponseDTO;

import java.util.List;

@RestController
@RequestMapping("/admin-core-service/learner/v1/fee")
public class FeeTrackingLearnerController {

    @Autowired
    private FeeTrackingService feeTrackingService;

    @Autowired
    private LearnerInstallmentPaymentService learnerInstallmentPaymentService;

    @GetMapping("/my-dues")
    public ResponseEntity<List<StudentFeePaymentDTO>> getMyDues(
            @RequestAttribute("user") CustomUserDetails user,
            @RequestParam("instituteId") String instituteId) {
        return ResponseEntity.ok(feeTrackingService.getStudentDues(user.getUserId(), instituteId));
    }

    @GetMapping("/my-receipts")
    public ResponseEntity<List<StudentFeeAllocationLedgerDTO>> getMyReceipts(
            @RequestAttribute("user") CustomUserDetails user,
            @RequestParam("instituteId") String instituteId) {
        return ResponseEntity.ok(feeTrackingService.getStudentReceipts(user.getUserId(), instituteId));
    }

    /**
     * Initiates an online gateway payment for one or more pending StudentFeePayment
     * rows (CPO installments) belonging to the calling learner. Reuses the existing
     * SCHOOL webhook branch — on success the rows flip to PAID via
     * FeeLedgerAllocationService and an Invoice is generated by InvoiceService.
     */
    @PostMapping("/pay-installments")
    public ResponseEntity<PaymentResponseDTO> payInstallments(
            @RequestAttribute("user") CustomUserDetails user,
            @RequestBody PayInstallmentsRequestDTO request) {
        return ResponseEntity.ok(learnerInstallmentPaymentService.payInstallments(user.getUserId(), request));
    }
}
