package vacademy.io.admin_core_service.features.tutorial_guide.service;

import com.itextpdf.styledxmlparser.jsoup.Jsoup;
import com.itextpdf.styledxmlparser.jsoup.nodes.Document;
import com.itextpdf.styledxmlparser.jsoup.nodes.Entities;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import vacademy.io.common.exceptions.VacademyException;

import java.io.ByteArrayOutputStream;

/**
 * Stateless HTML→PDF rendering for the learner-app how-to guide.
 *
 * <p>Same openhtmltopdf pipeline as {@code InvoiceService} /
 * {@code StudentReportPdfService} (Jsoup XHTML normalization, remote images
 * inlined as data URIs so the renderer never fetches over the network),
 * but with no persistence — the caller downloads the returned bytes directly.
 */
@Slf4j
@Service
public class TutorialGuidePdfService {

    // Guide HTML is generated by our own frontends; anything bigger than this
    // is malformed or abusive input, not a legitimate guide.
    private static final int MAX_HTML_LENGTH = 2_000_000;

    public byte[] renderGuidePdf(String htmlContent) {
        if (htmlContent == null || htmlContent.isBlank()) {
            throw new VacademyException("html is required");
        }
        if (htmlContent.length() > MAX_HTML_LENGTH) {
            throw new VacademyException("html too large");
        }

        try {
            boolean isCompleteHtml = htmlContent.trim().toLowerCase().startsWith("<!doctype")
                    || htmlContent.trim().toLowerCase().startsWith("<html");
            String htmlWithCss = isCompleteHtml ? htmlContent
                    : "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"/></head><body>" + htmlContent + "</body></html>";

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();

            String processedHtml = processImagesForPdf(htmlWithCss);
            String sanitized = sanitizeToXhtml(processedHtml);
            String xhtml = escapeBareAmpersands(sanitized);

            builder.withHtmlContent(xhtml, "file:///");
            builder.useDefaultPageSize(210f, 297f, PdfRendererBuilder.PageSizeUnits.MM); // A4 portrait
            builder.toStream(outputStream);
            builder.run();

            return outputStream.toByteArray();
        } catch (VacademyException e) {
            throw e;
        } catch (Exception e) {
            log.error("[TutorialGuide] Error generating PDF from HTML", e);
            throw new VacademyException("Failed to generate guide PDF: " + e.getMessage());
        }
    }

    private String sanitizeToXhtml(String html) {
        Document doc = Jsoup.parse(html);
        doc.outputSettings().syntax(Document.OutputSettings.Syntax.xml);
        doc.outputSettings().escapeMode(Entities.EscapeMode.xhtml);
        return doc.html();
    }

    private String processImagesForPdf(String html) {
        try {
            Document doc = Jsoup.parse(html);
            doc.select("img[src]").forEach(img -> {
                String src = img.attr("src");
                if (src != null && src.startsWith("http")) {
                    String base64 = convertUrlToBase64(src);
                    if (base64 != null) {
                        img.attr("src", base64);
                    }
                }
            });
            return doc.html();
        } catch (Exception e) {
            log.warn("[TutorialGuide] Error processing images, using original HTML: {}", e.getMessage());
            return html;
        }
    }

    private String convertUrlToBase64(String imageUrl) {
        try {
            java.net.URL url = new java.net.URL(imageUrl);
            java.net.HttpURLConnection conn = (java.net.HttpURLConnection) url.openConnection();
            conn.setConnectTimeout(5000);
            conn.setReadTimeout(10000);
            if (conn.getResponseCode() == 200) {
                try (java.io.InputStream is = conn.getInputStream();
                     ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
                    byte[] buf = new byte[4096];
                    int n;
                    while ((n = is.read(buf)) != -1) baos.write(buf, 0, n);
                    String ct = conn.getContentType() != null ? conn.getContentType() : "image/png";
                    return "data:" + ct + ";base64," + java.util.Base64.getEncoder().encodeToString(baos.toByteArray());
                }
            }
        } catch (Exception e) {
            log.warn("[TutorialGuide] Could not embed image {}: {}", imageUrl, e.getMessage());
        }
        return null;
    }

    private static String escapeBareAmpersands(String xhtml) {
        if (xhtml == null) return null;
        return xhtml.replaceAll("&(?![A-Za-z][A-Za-z0-9]*;|#[0-9]+;|#x[0-9A-Fa-f]+;)", "&amp;");
    }
}
