package vacademy.io.admin_core_service.features.telephony.controller;
import lombok.Data; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import vacademy.io.admin_core_service.features.telephony.apikey.AiCallApiKeyService; import vacademy.io.admin_core_service.features.telephony.apikey.entity.AiCallApiKey; import vacademy.io.admin_core_service.features.telephony.core.AiCallService; import vacademy.io.admin_core_service.features.telephony.core.dto.AiCallRequestDTO; import vacademy.io.admin_core_service.features.telephony.core.dto.AiCallResponseDTO; import vacademy.io.admin_core_service.features.telephony.enums.CallTrigger; import vacademy.io.admin_core_service.features.telephony.persistence.entity.TelephonyCallLog; import vacademy.io.admin_core_service.features.telephony.persistence.repository.TelephonyCallLogRepository; import java.util.*;
@RestController @RequestMapping("/admin-core-service/open/ai-calling/v1") @RequiredArgsConstructor
public class PublicAiCallingController {
 private final AiCallService aiCallService; private final TelephonyCallLogRepository callLogRepository; private final AiCallApiKeyService keyService;
 @PostMapping public Map<String,Object> create(@RequestHeader(value="X-API-Key",required=false) String key,@RequestBody CreateRequest q){String institute=keyService.verify(key).getInstituteId(); if(q==null||q.numbers==null||q.numbers.isEmpty()) bad("numbers is required"); if(q.agentId==null||q.agentId.isBlank()) bad("agentId is required"); if(q.numbers.size()>1000) bad("maximum 1000 numbers per request"); String mode=q.mode==null?"CLICK_TO_CALL":q.mode.toUpperCase(); if(!mode.equals("CLICK_TO_CALL")&&!mode.equals("BULK_CALL")) bad("mode must be CLICK_TO_CALL or BULK_CALL"); if("CLICK_TO_CALL".equals(mode)&&q.numbers.size()!=1) bad("CLICK_TO_CALL accepts one number"); List<AiCallResponseDTO> calls=q.numbers.stream().map(n->{AiCallRequestDTO r=new AiCallRequestDTO();r.setInstituteId(institute);r.setPhoneNumber(n);r.setUserId(UUID.randomUUID().toString());r.setCampaignId(q.campaignId==null?q.agentId:q.campaignId);r.setMetadata(q.metadata);return aiCallService.placeCall(r,null,CallTrigger.MANUAL);}).toList();return Map.of("mode",mode,"calls",calls);}
 @GetMapping("/{callId}") public Map<String,Object> status(@RequestHeader(value="X-API-Key",required=false) String key,@PathVariable String callId){String institute=keyService.verify(key).getInstituteId(); TelephonyCallLog r=callLogRepository.findById(callId).filter(c->institute.equals(c.getInstituteId())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Call not found")); Map<String,Object> m=new LinkedHashMap<>();m.put("callId",r.getId());m.put("status",r.getStatus());m.put("providerCallId",r.getProviderCallId());m.put("durationSeconds",r.getDurationSeconds());m.put("recordingUrl",r.getRecordingUrl());m.put("startedAt",r.getStartTime());m.put("completedAt",r.getEndTime());return m;}
 private void bad(String s){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}
 @Data public static class CreateRequest{private List<String> numbers;private String agentId;private String campaignId;private String mode;private Map<String,Object> metadata;}
}
