package vacademy.io.admin_core_service.features.tutorial_guide;

import org.junit.jupiter.api.Test;
import vacademy.io.admin_core_service.features.tutorial_guide.service.TutorialGuidePdfService;
import vacademy.io.common.exceptions.VacademyException;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Renders the real guide HTML (generated by the frontend builders — see
 * frontend-learner-dashboard-app/src/lib/tours/guide-html.ts) through the
 * actual openhtmltopdf pipeline. Catches paged-media CSS regressions
 * (@page margin boxes, counter(pages)) that a compile can't.
 */
class TutorialGuidePdfServiceTest {

    private final TutorialGuidePdfService service = new TutorialGuidePdfService();

    private String loadSampleGuide() throws Exception {
        try (InputStream is = getClass().getResourceAsStream("/tutorial_guide/sample-guide.html")) {
            assertNotNull(is, "sample-guide.html test resource missing");
            return new String(is.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    @Test
    void rendersFullGuideToValidPdf() throws Exception {
        byte[] pdf = service.renderGuidePdf(loadSampleGuide());

        assertTrue(pdf.length > 5_000, "PDF suspiciously small: " + pdf.length + " bytes");
        String magic = new String(pdf, 0, 5, StandardCharsets.US_ASCII);
        assertEquals("%PDF-", magic, "output is not a PDF");
    }

    @Test
    void rejectsBlankAndOversizedHtml() {
        assertThrows(VacademyException.class, () -> service.renderGuidePdf("  "));
        assertThrows(VacademyException.class, () -> service.renderGuidePdf("x".repeat(2_000_001)));
    }
}
