apiVersion: v1
kind: Service
metadata:
  name: admin-core-service
  namespace: default
spec:
  selector:
    app: admin-core-service
  ports:
    - name: http
      port: {{ .Values.services.admin_core_service.port }}
      targetPort: {{ .Values.services.admin_core_service.port }}
  type: NodePort