apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
  namespace: default
  labels:
    app: assessment-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: assessment-service
  template:
    metadata:
      labels:
        app: assessment-service
    spec:
      containers:
        - name: assessment-service
          image: {{ .Values.services.assessment_service.image.repository }}:{{ .Values.services.assessment_service.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "450Mi"
            limits:
              cpu: "250m"
              memory: "600Mi"
          livenessProbe:
            httpGet:
              path: /assessment-service/actuator/health
              port: {{ .Values.services.assessment_service.port }}
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /assessment-service/actuator/health
              port: {{ .Values.services.assessment_service.port }}
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /assessment-service/actuator/health
              port: {{ .Values.services.assessment_service.port }}
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: {{ .Values.services.assessment_service.port }}