apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: default
spec:
  selector:
    app: assessment-service
  ports:
    - name: http
      port: { { .Values.services.assessment_service.port } }
      targetPort: { { .Values.services.assessment_service.port } }
  type: NodePort