apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: default
spec:
  selector:
    app: community-service
  ports:
    - name: http
      port: {{ .Values.services.community_service.port }}
      targetPort: {{ .Values.services.community_service.port }}
  type: NodePort