apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: default
  labels:
    app: pgbouncer
spec:
  type: ClusterIP
  ports:
    - port: 6432
      targetPort: 6432
      protocol: TCP
      name: pgbouncer
  selector:
    app: pgbouncer
