_GOOGLE_VOICES: Dict[str, Dict[str, List[Dict[str, str]]]] = {
    "afrikaans": {
        "female": [
            {"id": "af-ZA-Standard-A", "name": "Standard (A)"},
        ],
        "male": [],
    },
    "arabic": {
        "female": [
            {"id": "ar-XA-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "ar-XA-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "ar-XA-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "ar-XA-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "ar-XA-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "ar-XA-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "ar-XA-Wavenet-D", "name": "WaveNet (D)"},
        ],
        "male": [
            {"id": "ar-XA-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "ar-XA-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "ar-XA-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "ar-XA-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "ar-XA-Wavenet-B", "name": "WaveNet (B)"},
        ],
    },
    "bulgarian": {
        "female": [],
        "male": [],
    },
    "catalan": {
        "female": [],
        "male": [],
    },
    "chinese": {
        "female": [
            {"id": "cmn-CN-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "cmn-CN-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "cmn-CN-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "cmn-CN-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "cmn-CN-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "cmn-CN-Wavenet-D", "name": "WaveNet (D)"},
            {"id": "cmn-CN-Standard-A", "name": "Standard (A)"},
            {"id": "cmn-CN-Standard-D", "name": "Standard (D)"},
        ],
        "male": [
            {"id": "cmn-CN-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "cmn-CN-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "cmn-CN-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "cmn-CN-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "cmn-CN-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "cmn-CN-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "cmn-CN-Standard-B", "name": "Standard (B)"},
            {"id": "cmn-CN-Standard-C", "name": "Standard (C)"},
        ],
    },
    "chinese (taiwan)": {
        "female": [
            {"id": "cmn-TW-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "cmn-TW-Standard-A", "name": "Standard (A)"},
        ],
        "male": [
            {"id": "cmn-TW-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "cmn-TW-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "cmn-TW-Standard-B", "name": "Standard (B)"},
            {"id": "cmn-TW-Standard-C", "name": "Standard (C)"},
        ],
    },
    "czech": {
        "female": [],
        "male": [],
    },
    "danish": {
        "female": [],
        "male": [
            {"id": "da-DK-Wavenet-G", "name": "WaveNet (G)"},
        ],
    },
    "dutch": {
        "female": [
            {"id": "nl-NL-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "nl-NL-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "nl-NL-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "nl-NL-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
        ],
        "male": [
            {"id": "nl-NL-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "nl-NL-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "nl-NL-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "nl-NL-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
        ],
    },
    "dutch (belgium)": {
        "female": [],
        "male": [],
    },
    "english (australia)": {
        "female": [
            {"id": "en-AU-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "en-AU-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "en-AU-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "en-AU-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "en-AU-Neural2-A", "name": "Neural2 (A)"},
            {"id": "en-AU-Neural2-C", "name": "Neural2 (C)"},
            {"id": "en-AU-News-E", "name": "News (E)"},
            {"id": "en-AU-News-F", "name": "News (F)"},
            {"id": "en-AU-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "en-AU-Wavenet-C", "name": "WaveNet (C)"},
        ],
        "male": [
            {"id": "en-AU-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "en-AU-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "en-AU-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "en-AU-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "en-AU-Neural2-B", "name": "Neural2 (B)"},
            {"id": "en-AU-Neural2-D", "name": "Neural2 (D)"},
            {"id": "en-AU-News-G", "name": "News (G)"},
            {"id": "en-AU-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "en-AU-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "english (india)": {
        "female": [
            {"id": "en-IN-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "en-IN-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "en-IN-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "en-IN-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "en-IN-Neural2-A", "name": "Neural2 (A)"},
            {"id": "en-IN-Neural2-D", "name": "Neural2 (D)"},
            {"id": "en-IN-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "en-IN-Wavenet-D", "name": "WaveNet (D)"},
        ],
        "male": [
            {"id": "en-IN-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "en-IN-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "en-IN-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "en-IN-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "en-IN-Neural2-B", "name": "Neural2 (B)"},
            {"id": "en-IN-Neural2-C", "name": "Neural2 (C)"},
            {"id": "en-IN-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "en-IN-Wavenet-C", "name": "WaveNet (C)"},
        ],
    },
    "english (uk)": {
        "female": [
            {"id": "en-GB-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "en-GB-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "en-GB-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "en-GB-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "en-GB-Neural2-A", "name": "Neural2 (A)"},
            {"id": "en-GB-Neural2-C", "name": "Neural2 (C)"},
            {"id": "en-GB-Neural2-F", "name": "Neural2 (F)"},
            {"id": "en-GB-News-G", "name": "News (G)"},
            {"id": "en-GB-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "en-GB-Wavenet-C", "name": "WaveNet (C)"},
        ],
        "male": [
            {"id": "en-GB-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "en-GB-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "en-GB-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "en-GB-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "en-GB-Neural2-B", "name": "Neural2 (B)"},
            {"id": "en-GB-Neural2-D", "name": "Neural2 (D)"},
            {"id": "en-GB-News-J", "name": "News (J)"},
            {"id": "en-GB-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "en-GB-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "english (us)": {
        "female": [
            {"id": "en-US-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "en-US-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "en-US-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "en-US-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "en-US-Neural2-C", "name": "Neural2 (C)"},
            {"id": "en-US-Neural2-F", "name": "Neural2 (F)"},
            {"id": "en-US-Neural2-H", "name": "Neural2 (H)"},
            {"id": "en-US-News-K", "name": "News (K)"},
            {"id": "en-US-News-L", "name": "News (L)"},
            {"id": "en-US-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "en-US-Wavenet-F", "name": "WaveNet (F)"},
        ],
        "male": [
            {"id": "en-US-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "en-US-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "en-US-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "en-US-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "en-US-Neural2-A", "name": "Neural2 (A)"},
            {"id": "en-US-Neural2-D", "name": "Neural2 (D)"},
            {"id": "en-US-Neural2-I", "name": "Neural2 (I)"},
            {"id": "en-US-Neural2-J", "name": "Neural2 (J)"},
            {"id": "en-US-News-N", "name": "News (N)"},
            {"id": "en-US-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "en-US-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "en-US-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "filipino": {
        "female": [
            {"id": "fil-PH-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "fil-PH-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "fil-PH-Standard-A", "name": "Standard (A)"},
        ],
        "male": [
            {"id": "fil-PH-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "fil-PH-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "finnish": {
        "female": [],
        "male": [],
    },
    "french": {
        "female": [
            {"id": "fr-FR-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "fr-FR-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "fr-FR-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "fr-FR-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
        ],
        "male": [
            {"id": "fr-FR-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "fr-FR-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "fr-FR-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "fr-FR-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
        ],
    },
    "french (canada)": {
        "female": [
            {"id": "fr-CA-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "fr-CA-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "fr-CA-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "fr-CA-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "fr-CA-Neural2-A", "name": "Neural2 (A)"},
            {"id": "fr-CA-Neural2-C", "name": "Neural2 (C)"},
            {"id": "fr-CA-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "fr-CA-Wavenet-C", "name": "WaveNet (C)"},
        ],
        "male": [
            {"id": "fr-CA-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "fr-CA-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "fr-CA-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "fr-CA-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "fr-CA-Neural2-B", "name": "Neural2 (B)"},
            {"id": "fr-CA-Neural2-D", "name": "Neural2 (D)"},
            {"id": "fr-CA-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "fr-CA-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "german": {
        "female": [
            {"id": "de-DE-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "de-DE-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "de-DE-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "de-DE-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
        ],
        "male": [
            {"id": "de-DE-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "de-DE-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "de-DE-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "de-DE-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
        ],
    },
    "greek": {
        "female": [],
        "male": [],
    },
    "hebrew": {
        "female": [
            {"id": "he-IL-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "he-IL-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "he-IL-Standard-A", "name": "Standard (A)"},
        ],
        "male": [
            {"id": "he-IL-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "he-IL-Wavenet-D", "name": "WaveNet (D)"},
            {"id": "he-IL-Standard-B", "name": "Standard (B)"},
        ],
    },
    "hungarian": {
        "female": [],
        "male": [],
    },
    "icelandic": {
        "female": [],
        "male": [],
    },
    "indonesian": {
        "female": [
            {"id": "id-ID-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "id-ID-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "id-ID-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "id-ID-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "id-ID-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "id-ID-Wavenet-D", "name": "WaveNet (D)"},
        ],
        "male": [
            {"id": "id-ID-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "id-ID-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "id-ID-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "id-ID-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "id-ID-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "id-ID-Wavenet-C", "name": "WaveNet (C)"},
        ],
    },
    "italian": {
        "female": [
            {"id": "it-IT-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "it-IT-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "it-IT-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "it-IT-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "it-IT-Neural2-A", "name": "Neural2 (A)"},
        ],
        "male": [
            {"id": "it-IT-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "it-IT-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "it-IT-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "it-IT-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
        ],
    },
    "japanese": {
        "female": [
            {"id": "ja-JP-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "ja-JP-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "ja-JP-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "ja-JP-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "ja-JP-Neural2-B", "name": "Neural2 (B)"},
            {"id": "ja-JP-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "ja-JP-Wavenet-B", "name": "WaveNet (B)"},
        ],
        "male": [
            {"id": "ja-JP-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "ja-JP-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "ja-JP-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "ja-JP-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "ja-JP-Neural2-C", "name": "Neural2 (C)"},
            {"id": "ja-JP-Neural2-D", "name": "Neural2 (D)"},
            {"id": "ja-JP-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "ja-JP-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "korean": {
        "female": [
            {"id": "ko-KR-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "ko-KR-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "ko-KR-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "ko-KR-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "ko-KR-Neural2-A", "name": "Neural2 (A)"},
            {"id": "ko-KR-Neural2-B", "name": "Neural2 (B)"},
            {"id": "ko-KR-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "ko-KR-Wavenet-B", "name": "WaveNet (B)"},
        ],
        "male": [
            {"id": "ko-KR-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "ko-KR-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "ko-KR-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "ko-KR-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "ko-KR-Neural2-C", "name": "Neural2 (C)"},
            {"id": "ko-KR-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "ko-KR-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "malay": {
        "female": [
            {"id": "ms-MY-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "ms-MY-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "ms-MY-Standard-A", "name": "Standard (A)"},
        ],
        "male": [
            {"id": "ms-MY-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "ms-MY-Wavenet-D", "name": "WaveNet (D)"},
            {"id": "ms-MY-Standard-B", "name": "Standard (B)"},
        ],
    },
    "norwegian": {
        "female": [],
        "male": [],
    },
    "polish": {
        "female": [
            {"id": "pl-PL-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "pl-PL-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "pl-PL-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "pl-PL-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
        ],
        "male": [
            {"id": "pl-PL-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "pl-PL-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "pl-PL-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "pl-PL-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
        ],
    },
    "portuguese (brazil)": {
        "female": [
            {"id": "pt-BR-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "pt-BR-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "pt-BR-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "pt-BR-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "pt-BR-Neural2-A", "name": "Neural2 (A)"},
            {"id": "pt-BR-Neural2-C", "name": "Neural2 (C)"},
            {"id": "pt-BR-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "pt-BR-Wavenet-C", "name": "WaveNet (C)"},
        ],
        "male": [
            {"id": "pt-BR-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "pt-BR-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "pt-BR-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "pt-BR-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "pt-BR-Neural2-B", "name": "Neural2 (B)"},
            {"id": "pt-BR-Wavenet-B", "name": "WaveNet (B)"},
        ],
    },
    "portuguese (portugal)": {
        "female": [],
        "male": [],
    },
    "romanian": {
        "female": [],
        "male": [],
    },
    "russian": {
        "female": [
            {"id": "ru-RU-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "ru-RU-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "ru-RU-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "ru-RU-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "ru-RU-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "ru-RU-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "ru-RU-Wavenet-E", "name": "WaveNet (E)"},
        ],
        "male": [
            {"id": "ru-RU-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "ru-RU-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "ru-RU-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "ru-RU-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "ru-RU-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "ru-RU-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
    "slovak": {
        "female": [],
        "male": [],
    },
    "spanish": {
        "female": [
            {"id": "es-ES-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "es-ES-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "es-ES-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "es-ES-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "es-ES-Neural2-A", "name": "Neural2 (A)"},
        ],
        "male": [
            {"id": "es-ES-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "es-ES-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "es-ES-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "es-ES-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "es-ES-Neural2-F", "name": "Neural2 (F)"},
        ],
    },
    "spanish (us)": {
        "female": [
            {"id": "es-US-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "es-US-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "es-US-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "es-US-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "es-US-Neural2-A", "name": "Neural2 (A)"},
            {"id": "es-US-News-F", "name": "News (F)"},
            {"id": "es-US-News-G", "name": "News (G)"},
            {"id": "es-US-Wavenet-A", "name": "WaveNet (A)"},
        ],
        "male": [
            {"id": "es-US-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "es-US-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "es-US-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "es-US-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "es-US-Neural2-B", "name": "Neural2 (B)"},
            {"id": "es-US-Neural2-C", "name": "Neural2 (C)"},
            {"id": "es-US-News-D", "name": "News (D)"},
            {"id": "es-US-News-E", "name": "News (E)"},
            {"id": "es-US-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "es-US-Wavenet-C", "name": "WaveNet (C)"},
        ],
    },
    "swedish": {
        "female": [
            {"id": "sv-SE-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "sv-SE-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "sv-SE-Wavenet-D", "name": "WaveNet (D)"},
        ],
        "male": [
            {"id": "sv-SE-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "sv-SE-Wavenet-E", "name": "WaveNet (E)"},
            {"id": "sv-SE-Wavenet-F", "name": "WaveNet (F)"},
        ],
    },
    "thai": {
        "female": [
            {"id": "th-TH-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "th-TH-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "th-TH-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "th-TH-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "th-TH-Neural2-C", "name": "Neural2 (C)"},
            {"id": "th-TH-Standard-A", "name": "Standard (A)"},
        ],
        "male": [
            {"id": "th-TH-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "th-TH-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "th-TH-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "th-TH-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
        ],
    },
    "turkish": {
        "female": [
            {"id": "tr-TR-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "tr-TR-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "tr-TR-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "tr-TR-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "tr-TR-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "tr-TR-Wavenet-C", "name": "WaveNet (C)"},
            {"id": "tr-TR-Wavenet-D", "name": "WaveNet (D)"},
            {"id": "tr-TR-Wavenet-E", "name": "WaveNet (E)"},
        ],
        "male": [
            {"id": "tr-TR-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "tr-TR-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "tr-TR-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "tr-TR-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "tr-TR-Wavenet-B", "name": "WaveNet (B)"},
        ],
    },
    "ukrainian": {
        "female": [
            {"id": "uk-UA-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "uk-UA-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "uk-UA-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "uk-UA-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
        ],
        "male": [
            {"id": "uk-UA-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "uk-UA-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "uk-UA-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "uk-UA-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
        ],
    },
    "urdu": {
        "female": [
            {"id": "ur-IN-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "ur-IN-Standard-A", "name": "Standard (A)"},
        ],
        "male": [
            {"id": "ur-IN-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "ur-IN-Standard-B", "name": "Standard (B)"},
        ],
    },
    "vietnamese": {
        "female": [
            {"id": "vi-VN-Chirp3-HD-Aoede", "name": "Chirp3 HD (Aoede)"},
            {"id": "vi-VN-Chirp3-HD-Kore", "name": "Chirp3 HD (Kore)"},
            {"id": "vi-VN-Chirp3-HD-Leda", "name": "Chirp3 HD (Leda)"},
            {"id": "vi-VN-Chirp3-HD-Zephyr", "name": "Chirp3 HD (Zephyr)"},
            {"id": "vi-VN-Wavenet-A", "name": "WaveNet (A)"},
            {"id": "vi-VN-Wavenet-C", "name": "WaveNet (C)"},
        ],
        "male": [
            {"id": "vi-VN-Chirp3-HD-Charon", "name": "Chirp3 HD (Charon)"},
            {"id": "vi-VN-Chirp3-HD-Fenrir", "name": "Chirp3 HD (Fenrir)"},
            {"id": "vi-VN-Chirp3-HD-Orus", "name": "Chirp3 HD (Orus)"},
            {"id": "vi-VN-Chirp3-HD-Puck", "name": "Chirp3 HD (Puck)"},
            {"id": "vi-VN-Wavenet-B", "name": "WaveNet (B)"},
            {"id": "vi-VN-Wavenet-D", "name": "WaveNet (D)"},
        ],
    },
}
