package vacademy.io.admin_core_service.features.user_subscription.dto.markdown;

public enum MarkdownErrorCode {
    PACKAGE_SESSION_NOT_FOUND,
    NO_ACTIVE_PAYMENT_OPTION,
    FREE_OPTION_NOT_DISCOUNTABLE,
    INSTITUTE_DEFAULT_OPTION_NOT_DISCOUNTABLE,
    NO_ACTIVE_PAYMENT_PLAN,
    MULTIPLE_ACTIVE_PAYMENT_PLANS,
    PAYMENT_OPTION_SHARED_WITH_OTHERS,
    INVALID_MARKDOWN_VALUE,
    CPO_OPTION_NOT_SUPPORTED
}
