name: Deploy Media to LKE

on:
  push:
    branches:
      - main
    paths:
      - 'media_service/**'

jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Authenticate GitHub Package Registry
        env:
          JAVA_TOKEN: ${{ secrets.JAVA_TOKEN }}
          ACCESS_GITHUB_USERNAME: ${{ secrets.ACCESS_GITHUB_USERNAME }}
        run: |
          echo "${JAVA_TOKEN}" | docker login ghcr.io -u ${ACCESS_GITHUB_USERNAME} --password-stdin
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${ACCESS_GITHUB_USERNAME}</username><password>${JAVA_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml


      - name: Build Project
        working-directory: ./media_service
        env:
          JAVA_TOKEN: ${{ secrets.JAVA_TOKEN }}
          ACCESS_GITHUB_USERNAME: ${{ secrets.ACCESS_GITHUB_USERNAME }}
        run: mvn -s settings.xml clean install -DskipTests

      # To push to ECR you need to login through us-east-1
      # https://github.com/aws-actions/amazon-ecr-login/issues/587
      # https://github.com/aws-actions/amazon-ecr-login?tab=readme-ov-file#troubleshooting
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ./media_service
        env:
          ECR_REGISTRY: public.ecr.aws/e0x1f4p4
          IMAGE_TAG: latest
          REPOSITORY: media-service/media-service-repo
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
          ACCESS_GITHUB_USERNAME: ${{ secrets.ACCESS_GITHUB_USERNAME }}
          JAVA_TOKEN: ${{ secrets.JAVA_TOKEN }}
          S3_AWS_ACCESS_KEY: ${{ secrets.S3_AWS_ACCESS_KEY }}
          S3_AWS_ACCESS_SECRET: ${{ secrets.S3_AWS_ACCESS_SECRET }}
          S3_AWS_REGION: ${{ secrets.S3_AWS_REGION }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

        run: |
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG . --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} --build-arg ACCESS_GITHUB_USERNAME=${ACCESS_GITHUB_USERNAME} --build-arg JAVA_TOKEN=${JAVA_TOKEN} --build-arg SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "Docker Image Link = $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG"

      # Get the KUBECONFIG from : https://cloud.linode.com/kubernetes/clusters/189301/summary

      # TODO: This kubeconfig is global kubeconfig with access to whole cluster
      # In production refrain from using this and use k8s service account with limited access
      # Each service account has permissions like IAM and each has its own kubeconfig
      # replace global kubeconfig with service account's kubeconfig
      # https://www.linode.com/content/terraforming-kubernetes-github-actions/
      # https://nicwortel.nl/blog/2022/continuous-deployment-to-kubernetes-with-github-actions
      - name: Connect to LKE kubernetes cluster
        id: connect-to-k8s-cluster
        uses: Azure/k8s-set-context@v4.0.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.VACADEMY_STAGE_KUBECONFIG}}

      - name: Deploy to Kubernetes
        run: |
          kubectl set env deployment/media-service \
            DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            DB_USERNAME=${{ secrets.DB_USERNAME }} \
            APP_USERNAME=${{ secrets.APP_USERNAME }} \
            APP_PASSWORD=${{ secrets.APP_PASSWORD }} \
            AUTH_SERVER_BASE_URL=${{ secrets.AUTH_SERVER_BASE_URL }} \
            ASSESSMENT_SERVER_BASE_URL=${{ secrets.ASSESSMENT_SERVER_BASE_URL }} \
            CLOUD_FRONT_URL=${{ secrets.CLOUD_FRONT_URL }} \
            MEDIA_SERVICE_DB_URL=${{ secrets.MEDIA_SERVICE_DB_URL }} \
            S3_AWS_ACCESS_KEY=${{ secrets.S3_AWS_ACCESS_KEY }} \
            S3_AWS_ACCESS_SECRET=${{ secrets.S3_AWS_ACCESS_SECRET }} \
            S3_AWS_REGION=${{ secrets.S3_AWS_REGION }} \
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            AWS_S3_PUBLIC_BUCKET=${{ secrets.AWS_S3_PUBLIC_BUCKET }} \
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }} \
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} \
            UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }} \
            DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }} \
            SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Restart deployment
        id: restart-deployment
        env:
          DEPLOYMENT_NAME: media-service
          NAMESPACE: default
        run: |
          kubectl rollout restart deployment $DEPLOYMENT_NAME --namespace $NAMESPACE
