# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Common Library

on:
  push:
    branches:
      - main
    paths:
      - 'common_service/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Build with Maven
        run: mvn -B package --file common_service/pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy --file common_service/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}

